apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
      tier: {{ .Values.db.name }}
      track: stable
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
        tier: {{ .Values.db.name }}
        track: stable
    spec:
        volumes:
        - name: crypto-pv-storage
          persistentVolumeClaim:
             claimName: crypto-pv-claim
        containers:
        - name: {{ .Values.db.name }}
          image: {{ .Values.db.version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
          - name: POSTGRES_USER
            value: {{ .Values.db.env.db_user.value}}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.db.env.db_password.value}}
          - name: POSTGRES_DB
            value: {{ .Values.db.env.db_name.value}}
          ports:
          - name: http
            containerPort: {{ .Values.db.port }}
          volumeMounts:
          - mountPath: {{ .Values.db.mountPath }}
            name: crypto-pv-storage