apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crypto-ingress
spec:
 rules:
 - host: crypto-report
   http:
     paths:   
     - backend:
         serviceName: {{ .Values.backendReporter.name }}
         servicePort: {{ .Values.backendReporter.port }}     
 - host: crypto-user
   http:
     paths:   
     - backend:
         serviceName: {{ .Values.backendUser.name }}
         servicePort: {{ .Values.backendUser.port }}              
 - host: crypto
   http:
     paths:   
     - backend:
         serviceName: {{ .Values.frontend.name }}
         servicePort: {{ .Values.frontend.port }}         