apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crypto-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: crypto
   http:
     paths:   
     - path: /api(/|$)(.*)
       backend:
         serviceName: {{ .Values.backendReporter.name }}
         servicePort: {{ .Values.backendReporter.port }}     
     - path: /user(/|$)(.*)
       backend:
         serviceName: {{ .Values.backendUser.name }}
         servicePort: {{ .Values.backendUser.port }}              
     - path: /?(.*)
       backend:
         serviceName: {{ .Values.frontend.name }}
         servicePort: {{ .Values.frontend.port }}