apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crypto-ingress-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
 rules:
 - host: minikube
   http:
     paths:     
     - path: /api/?(.*)
       backend:
         serviceName: {{ .Values.backendReporter.name }}
         servicePort: {{ .Values.backendReporter.port }}