apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendReporter.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backendReporter.name }}
      tier: {{ .Values.backendReporter.name }}
      track: stable
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendReporter.name }}
        tier: {{ .Values.backendReporter.name }}
        track: stable
    spec:
      containers:
      - name: {{ .Values.backendReporter.name }}
        image: {{ .Values.backendReporter.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.backendReporter.port }}
        env:
        - name: {{ .Values.backendReporter.env.crypto_collector.name }}
          value: {{ .Values.backendCollector.name }}
        - name: {{ .Values.backendReporter.env.crypto_collector_port.name }}
          value: {{ .Values.backendCollector.port | quote}}          