replicaCount: 1

nameSpace: crypto

imagePullPolicy: Always

backendCollector:
    name: backend-collector
    image: udvaridonat/donat-crypto:cryptoCollector
    port: 8080
            
backendReporter:
    name: backend-reporter
    image: udvaridonat/donat-crypto:cryptoReporter
    port: 8080
    env:
        crypto_collector:
            name: CRYPTO_COLLECTOR            
        crypto_collector_port:
            name: CRYPTO_COLLECTOR_PORT            
    
backendUser:
    name: backend-user
    image: udvaridonat/donat-crypto:cryptoUser
    port: 8080    
    env:
        crypto_reporter:
            name: CRYPTO_REPORTER            
        crypto_reporter_port:
            name: CRYPTO_REPORTER_PORT                
            
frontend:            
    name: frontend
    image: udvaridonat/donat-crypto:frontend
    port: 4200
    env:
        crypto_report:
            name: CRYPTO_REPORT 
        crypto_user:
            name: CRYPTO_USER
    
volume:
    path: /data/pvCrypto/
    
db:
    name: postgres
    port: 5432
    version: postgres:12.2
    mountPath: /var/lib/postgresql/data
    env:
        db_service:
            name: DB_SERVICE
            value: postgres
        db_user:
            name: DB_USER
            value: postgres
        db_password:
            name: DB_PASSWORD
            value: crypto77
        db_name:
            name: DB_NAME            
            value: postgres         
    
jms:
    name: jms
    port: 61616
    version: vromero/activemq-artemis    
    env:
        jms_name:
            name: JMS_NAME
            value: artemis
        jms_password:
            name: JMS_PASSWORD
            value: simetraehcapa
